module TestUtil where

import Phascal.Arm
import Phascal.Parser
import Phascal.Build

import System.Exit
import System.Process
import System.Posix.Process
import System.FilePath.Posix
import System.Directory

import Control.Monad (join)

-- | @compileText input@ is the assembly generated by compiling the
-- program whose source code is @input@.
--
-- It is an error to pass this function a ill-typed program.
compileText :: String -> String
compileText src = do
    let
        (Right [ast]) = parse "<test-program>" src
        directives = compileProgram ast
      in
        join (map formatDirective directives)

getPathFor :: String -> IO String
getPathFor name = do
    pid <- getProcessID
    let path = "test-scratch" </> show pid </> name
    createDirectoryIfMissing True path
    return path

buildAsm :: String -> String -> IO String
buildAsm testName src = do
    path <- getPathFor testName
    let [asm, obj, exe] = map (path </>) ["test.s", "test.o", "test"]
    writeFile asm src
    assemble obj asm
    link exe obj
    return exe

runAsm :: String -> String -> IO ExitCode
runAsm testName src = do
    exepath <- buildAsm testName src
    spawnProcess "qemu-arm" [exepath] >>= waitForProcess
